package:
  name: ros
  version: 2020.08.25

source:
  - git_url: https://github.com/ros-gbp/joystick_drivers-release.git
    git_rev: release/melodic/joy/1.14.0-1
    folder: ros-melodic-joy/src/work

build:
  number: 1

about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge
outputs:
  - package:
      name: ros-melodic-joy
      version: 1.14.0
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - sel(unix): make
        - cmake
      host:
        - python
        - ros-melodic-catkin
        - ros-melodic-diagnostic-updater
        - ros-melodic-rosbag
        - ros-melodic-roscpp
        - ros-melodic-roslint
        - ros-melodic-sensor-msgs
      run:
        - python
        - ros-melodic-diagnostic-updater
        - ros-melodic-roscpp
        - ros-melodic-sensor-msgs
    build:
      script: build_catkin.sh
