package:
  name: ros
  version: 2020.08.25

source:
  - git_url: https://github.com/ros-gbp/class_loader-release.git
    git_rev: release/melodic/class_loader/0.4.1-0
    folder: ros-melodic-class-loader/src/work
    patches:
      - /home/wolfv/Programs/vinca/examples/patch/ros-melodic-class-loader.patch
  - git_url: https://github.com/frankaemika/libfranka-release.git
    git_rev: release/melodic/libfranka/0.8.0-1
    folder: ros-melodic-libfranka/src/work
    patches:
      - /home/wolfv/Programs/vinca/examples/patch/ros-melodic-libfranka.patch

build:
  number: 1

about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge
outputs:
  - package:
      name: ros-melodic-class-loader
      version: 0.4.1
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - sel(unix): make
        - cmake
      host:
        - boost
        - console_bridge
        - poco
        - python
        - ros-melodic-catkin
        - ros-melodic-cmake-modules
      run:
        - boost
        - console_bridge
        - poco
        - python
    build:
      script: build_catkin.sh
  - package:
      name: ros-melodic-libfranka
      version: 0.8.0
    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - "{{ compiler('c') }}"
        - ninja
        - sel(unix): make
        - cmake
      host:
        - cmake
        - eigen
        - poco
        - python
      run:
        - poco
        - python
        - ros-melodic-catkin
    build:
      script: build_catkin.sh
